@startuml classes
set namespaceSeparator none
class "Article" as zeeguu.core.model.article.Article {
}
class "ArticleDifficultyFeedback" as zeeguu.core.model.article_difficulty_feedback.ArticleDifficultyFeedback {
}
class "ArticleWord" as zeeguu.core.model.article_word.ArticleWord {
}
class "ArticlesCache" as zeeguu.core.model.articles_cache.ArticlesCache {
}
class "Bookmark" as zeeguu.core.model.bookmark.Bookmark {
}
class "BookmarkPriorityARTS" as zeeguu.core.model.bookmark_priority_arts.BookmarkPriorityARTS {
}
class "Cohort" as zeeguu.core.model.cohort.Cohort {
}
class "CohortArticleMap" as zeeguu.core.model.cohort_article_map.CohortArticleMap {
}
class "DifficultyLingoRank" as zeeguu.core.model.difficulty_lingo_rank.DifficultyLingoRank {
}
class "DomainName" as zeeguu.core.model.domain_name.DomainName {
}
class "Exercise" as zeeguu.core.model.exercise.Exercise {
}
class "ExerciseOutcome" as zeeguu.core.model.exercise_outcome.ExerciseOutcome {
}
class "ExerciseSource" as zeeguu.core.model.exercise_source.ExerciseSource {
}
class "Language" as zeeguu.core.model.language.Language {
}
class "LocalizedTopic" as zeeguu.core.model.localized_topic.LocalizedTopic {
}
class "PersonalCopy" as zeeguu.core.model.personal_copy.PersonalCopy {
}
class "RSSFeed" as zeeguu.core.model.feed.RSSFeed {
}
class "Search" as zeeguu.core.model.search.Search {
}
class "SearchFilter" as zeeguu.core.model.search_filter.SearchFilter {
}
class "SearchSubscription" as zeeguu.core.model.search_subscription.SearchSubscription {
}
class "Session" as zeeguu.core.model.session.Session {
}
class "SortedExerciseLog" as zeeguu.core.model.sorted_exercise_log.SortedExerciseLog {
}
class "StarredArticle" as zeeguu.core.model.starred_article.StarredArticle {
}
class "Teacher" as zeeguu.core.model.teacher.Teacher {
}
class "TeacherCohortMap" as zeeguu.core.model.teacher_cohort_map.TeacherCohortMap {
}
class "Text" as zeeguu.core.model.text.Text {
}
class "Topic" as zeeguu.core.model.topic.Topic {
}
class "TopicFilter" as zeeguu.core.model.topic_filter.TopicFilter {
}
class "TopicSubscription" as zeeguu.core.model.topic_subscription.TopicSubscription {
}
class "UniqueCode" as zeeguu.core.model.unique_code.UniqueCode {
}
class "Url" as zeeguu.core.model.url.Url {
}
class "User" as zeeguu.core.model.user.User {
}
class "UserActivityData" as zeeguu.core.model.user_activitiy_data.UserActivityData {
}
class "UserArticle" as zeeguu.core.model.user_article.UserArticle {
}
class "UserExerciseSession" as zeeguu.core.model.user_exercise_session.UserExerciseSession {
}
class "UserLanguage" as zeeguu.core.model.user_language.UserLanguage {
}
class "UserPreference" as zeeguu.core.model.user_preference.UserPreference {
}
class "UserReadingSession" as zeeguu.core.model.user_reading_session.UserReadingSession {
}
class "UserWord" as zeeguu.core.model.user_word.UserWord {
}
class "WatchEventType" as zeeguu.core.model.smartwatch.watch_event_type.WatchEventType {
}
class "WatchInteractionEvent" as zeeguu.core.model.smartwatch.watch_interaction_event.WatchInteractionEvent {
}
class "WordInteractionEvent" as zeeguu.core.model.word_knowledge.word_interaction_history.WordInteractionEvent {
}
class "WordInteractionHistory" as zeeguu.core.model.word_knowledge.word_interaction_history.WordInteractionHistory {
}
class "WordToStudy" as zeeguu.core.model.word_to_study.WordToStudy {
}
zeeguu.core.model.domain_name.DomainName --* zeeguu.core.model.url.Url : domain
zeeguu.core.model.user.User --o zeeguu.core.model.user_preference.UserPreference : user
zeeguu.core.model.user.User --o zeeguu.core.model.word_knowledge.word_interaction_history.WordInteractionHistory : user
zeeguu.core.model.user_word.UserWord --o zeeguu.core.model.bookmark.Bookmark : origin
zeeguu.core.model.user_word.UserWord --o zeeguu.core.model.bookmark.Bookmark : translation
zeeguu.core.model.user_word.UserWord --o zeeguu.core.model.word_knowledge.word_interaction_history.WordInteractionHistory : word
@enduml
