@startuml packages
set namespaceSeparator none
package "__init__" as __init__ {
}
package "archrcover" as archrcover {
}
package "archrcover.download_repo" as archrcover.download_repo {
}
package "zeeguu.core.model" as zeeguu.core.model {
}
package "zeeguu.core.model.article" as zeeguu.core.model.article {
}
package "zeeguu.core.model.article_difficulty_feedback" as zeeguu.core.model.article_difficulty_feedback {
}
package "zeeguu.core.model.article_word" as zeeguu.core.model.article_word {
}
package "zeeguu.core.model.articles_cache" as zeeguu.core.model.articles_cache {
}
package "zeeguu.core.model.bookmark" as zeeguu.core.model.bookmark {
}
package "zeeguu.core.model.bookmark_priority_arts" as zeeguu.core.model.bookmark_priority_arts {
}
package "zeeguu.core.model.cohort" as zeeguu.core.model.cohort {
}
package "zeeguu.core.model.cohort_article_map" as zeeguu.core.model.cohort_article_map {
}
package "zeeguu.core.model.difficulty_lingo_rank" as zeeguu.core.model.difficulty_lingo_rank {
}
package "zeeguu.core.model.domain_name" as zeeguu.core.model.domain_name {
}
package "zeeguu.core.model.exercise" as zeeguu.core.model.exercise {
}
package "zeeguu.core.model.exercise_outcome" as zeeguu.core.model.exercise_outcome {
}
package "zeeguu.core.model.exercise_source" as zeeguu.core.model.exercise_source {
}
package "zeeguu.core.model.feed" as zeeguu.core.model.feed {
}
package "zeeguu.core.model.language" as zeeguu.core.model.language {
}
package "zeeguu.core.model.learner_stats" as zeeguu.core.model.learner_stats {
}
package "zeeguu.core.model.learner_stats.learner_stats" as zeeguu.core.model.learner_stats.learner_stats {
}
package "zeeguu.core.model.localized_topic" as zeeguu.core.model.localized_topic {
}
package "zeeguu.core.model.personal_copy" as zeeguu.core.model.personal_copy {
}
package "zeeguu.core.model.search" as zeeguu.core.model.search {
}
package "zeeguu.core.model.search_filter" as zeeguu.core.model.search_filter {
}
package "zeeguu.core.model.search_subscription" as zeeguu.core.model.search_subscription {
}
package "zeeguu.core.model.session" as zeeguu.core.model.session {
}
package "zeeguu.core.model.smartwatch" as zeeguu.core.model.smartwatch {
}
package "zeeguu.core.model.smartwatch.watch_event_type" as zeeguu.core.model.smartwatch.watch_event_type {
}
package "zeeguu.core.model.smartwatch.watch_interaction_event" as zeeguu.core.model.smartwatch.watch_interaction_event {
}
package "zeeguu.core.model.sorted_exercise_log" as zeeguu.core.model.sorted_exercise_log {
}
package "zeeguu.core.model.starred_article" as zeeguu.core.model.starred_article {
}
package "zeeguu.core.model.teacher" as zeeguu.core.model.teacher {
}
package "zeeguu.core.model.teacher_cohort_map" as zeeguu.core.model.teacher_cohort_map {
}
package "zeeguu.core.model.text" as zeeguu.core.model.text {
}
package "zeeguu.core.model.topic" as zeeguu.core.model.topic {
}
package "zeeguu.core.model.topic_filter" as zeeguu.core.model.topic_filter {
}
package "zeeguu.core.model.topic_subscription" as zeeguu.core.model.topic_subscription {
}
package "zeeguu.core.model.unique_code" as zeeguu.core.model.unique_code {
}
package "zeeguu.core.model.url" as zeeguu.core.model.url {
}
package "zeeguu.core.model.user" as zeeguu.core.model.user {
}
package "zeeguu.core.model.user_activitiy_data" as zeeguu.core.model.user_activitiy_data {
}
package "zeeguu.core.model.user_article" as zeeguu.core.model.user_article {
}
package "zeeguu.core.model.user_exercise_session" as zeeguu.core.model.user_exercise_session {
}
package "zeeguu.core.model.user_language" as zeeguu.core.model.user_language {
}
package "zeeguu.core.model.user_preference" as zeeguu.core.model.user_preference {
}
package "zeeguu.core.model.user_reading_session" as zeeguu.core.model.user_reading_session {
}
package "zeeguu.core.model.user_word" as zeeguu.core.model.user_word {
}
package "zeeguu.core.model.word_knowledge" as zeeguu.core.model.word_knowledge {
}
package "zeeguu.core.model.word_knowledge.word_interaction_history" as zeeguu.core.model.word_knowledge.word_interaction_history {
}
package "zeeguu.core.model.word_to_study" as zeeguu.core.model.word_to_study {
}
zeeguu.core.model --> zeeguu.core.model.article
zeeguu.core.model --> zeeguu.core.model.article_difficulty_feedback
zeeguu.core.model --> zeeguu.core.model.article_word
zeeguu.core.model --> zeeguu.core.model.articles_cache
zeeguu.core.model --> zeeguu.core.model.bookmark
zeeguu.core.model --> zeeguu.core.model.bookmark_priority_arts
zeeguu.core.model --> zeeguu.core.model.cohort
zeeguu.core.model --> zeeguu.core.model.cohort_article_map
zeeguu.core.model --> zeeguu.core.model.difficulty_lingo_rank
zeeguu.core.model --> zeeguu.core.model.domain_name
zeeguu.core.model --> zeeguu.core.model.exercise
zeeguu.core.model --> zeeguu.core.model.exercise_outcome
zeeguu.core.model --> zeeguu.core.model.exercise_source
zeeguu.core.model --> zeeguu.core.model.feed
zeeguu.core.model --> zeeguu.core.model.language
zeeguu.core.model --> zeeguu.core.model.localized_topic
zeeguu.core.model --> zeeguu.core.model.personal_copy
zeeguu.core.model --> zeeguu.core.model.search
zeeguu.core.model --> zeeguu.core.model.search_filter
zeeguu.core.model --> zeeguu.core.model.search_subscription
zeeguu.core.model --> zeeguu.core.model.session
zeeguu.core.model --> zeeguu.core.model.smartwatch.watch_event_type
zeeguu.core.model --> zeeguu.core.model.smartwatch.watch_interaction_event
zeeguu.core.model --> zeeguu.core.model.teacher
zeeguu.core.model --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model --> zeeguu.core.model.text
zeeguu.core.model --> zeeguu.core.model.topic
zeeguu.core.model --> zeeguu.core.model.topic_filter
zeeguu.core.model --> zeeguu.core.model.topic_subscription
zeeguu.core.model --> zeeguu.core.model.unique_code
zeeguu.core.model --> zeeguu.core.model.url
zeeguu.core.model --> zeeguu.core.model.user
zeeguu.core.model --> zeeguu.core.model.user_activitiy_data
zeeguu.core.model --> zeeguu.core.model.user_article
zeeguu.core.model --> zeeguu.core.model.user_exercise_session
zeeguu.core.model --> zeeguu.core.model.user_language
zeeguu.core.model --> zeeguu.core.model.user_preference
zeeguu.core.model --> zeeguu.core.model.user_reading_session
zeeguu.core.model --> zeeguu.core.model.user_word
zeeguu.core.model --> zeeguu.core.model.word_knowledge.word_interaction_history
zeeguu.core.model --> zeeguu.core.model.word_to_study
zeeguu.core.model.article --> zeeguu.core.model
zeeguu.core.model.article --> zeeguu.core.model.feed
zeeguu.core.model.article --> zeeguu.core.model.language
zeeguu.core.model.article --> zeeguu.core.model.topic
zeeguu.core.model.article --> zeeguu.core.model.url
zeeguu.core.model.article --> zeeguu.core.model.user
zeeguu.core.model.article --> zeeguu.core.model.user_article
zeeguu.core.model.article_difficulty_feedback --> zeeguu.core.model
zeeguu.core.model.article_word --> zeeguu.core.model.article
zeeguu.core.model.articles_cache --> zeeguu.core.model
zeeguu.core.model.articles_cache --> zeeguu.core.model.article
zeeguu.core.model.bookmark --> zeeguu.core.model
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise_outcome
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise_source
zeeguu.core.model.bookmark --> zeeguu.core.model.language
zeeguu.core.model.bookmark --> zeeguu.core.model.sorted_exercise_log
zeeguu.core.model.bookmark --> zeeguu.core.model.text
zeeguu.core.model.bookmark --> zeeguu.core.model.user
zeeguu.core.model.bookmark --> zeeguu.core.model.user_word
zeeguu.core.model.bookmark_priority_arts --> zeeguu.core.model.bookmark
zeeguu.core.model.cohort --> zeeguu.core.model.language
zeeguu.core.model.cohort --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model.cohort --> zeeguu.core.model.user
zeeguu.core.model.cohort_article_map --> zeeguu.core.model.article
zeeguu.core.model.cohort_article_map --> zeeguu.core.model.cohort
zeeguu.core.model.difficulty_lingo_rank --> zeeguu.core.model.article
zeeguu.core.model.exercise --> zeeguu.core.model.bookmark
zeeguu.core.model.exercise --> zeeguu.core.model.exercise_outcome
zeeguu.core.model.exercise --> zeeguu.core.model.exercise_source
zeeguu.core.model.feed --> zeeguu.core.model
zeeguu.core.model.feed --> zeeguu.core.model.language
zeeguu.core.model.feed --> zeeguu.core.model.url
zeeguu.core.model.language --> zeeguu.core.model
zeeguu.core.model.localized_topic --> zeeguu.core.model
zeeguu.core.model.localized_topic --> zeeguu.core.model.language
zeeguu.core.model.localized_topic --> zeeguu.core.model.topic
zeeguu.core.model.personal_copy --> zeeguu.core.model.article
zeeguu.core.model.personal_copy --> zeeguu.core.model.user
zeeguu.core.model.search --> zeeguu.core.model
zeeguu.core.model.search_filter --> zeeguu.core.model.search
zeeguu.core.model.search_filter --> zeeguu.core.model.user
zeeguu.core.model.search_subscription --> zeeguu.core.model.search
zeeguu.core.model.search_subscription --> zeeguu.core.model.user
zeeguu.core.model.session --> zeeguu.core.model.user
zeeguu.core.model.smartwatch.watch_interaction_event --> zeeguu.core.model.bookmark
zeeguu.core.model.starred_article --> zeeguu.core.model
zeeguu.core.model.starred_article --> zeeguu.core.model.language
zeeguu.core.model.teacher --> zeeguu.core.model
zeeguu.core.model.teacher --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model.teacher_cohort_map --> zeeguu.core.model
zeeguu.core.model.teacher_cohort_map --> zeeguu.core.model.cohort
zeeguu.core.model.text --> zeeguu.core.model
zeeguu.core.model.text --> zeeguu.core.model.language
zeeguu.core.model.text --> zeeguu.core.model.url
zeeguu.core.model.text --> zeeguu.core.model.user_word
zeeguu.core.model.topic --> zeeguu.core.model
zeeguu.core.model.topic_filter --> zeeguu.core.model.topic
zeeguu.core.model.topic_filter --> zeeguu.core.model.user
zeeguu.core.model.topic_subscription --> zeeguu.core.model.topic
zeeguu.core.model.topic_subscription --> zeeguu.core.model.user
zeeguu.core.model.url --> zeeguu.core.model.domain_name
zeeguu.core.model.user --> zeeguu.core.model
zeeguu.core.model.user --> zeeguu.core.model.article
zeeguu.core.model.user --> zeeguu.core.model.bookmark
zeeguu.core.model.user --> zeeguu.core.model.cohort
zeeguu.core.model.user --> zeeguu.core.model.learner_stats.learner_stats
zeeguu.core.model.user --> zeeguu.core.model.user_article
zeeguu.core.model.user --> zeeguu.core.model.user_preference
zeeguu.core.model.user --> zeeguu.core.model.user_reading_session
zeeguu.core.model.user_activitiy_data --> zeeguu.core.model
zeeguu.core.model.user_activitiy_data --> zeeguu.core.model.user_reading_session
zeeguu.core.model.user_article --> zeeguu.core.model
zeeguu.core.model.user_article --> zeeguu.core.model.personal_copy
zeeguu.core.model.user_exercise_session --> zeeguu.core.model.user
zeeguu.core.model.user_language --> zeeguu.core.model
zeeguu.core.model.user_language --> zeeguu.core.model.language
zeeguu.core.model.user_preference --> zeeguu.core.model
zeeguu.core.model.user_reading_session --> zeeguu.core.model
zeeguu.core.model.user_word --> zeeguu.core.model.language
zeeguu.core.model.word_knowledge.word_interaction_history --> zeeguu.core.model
zeeguu.core.model.word_to_study --> zeeguu.core.model.bookmark
zeeguu.core.model.word_to_study --> zeeguu.core.model.language
zeeguu.core.model.word_to_study --> zeeguu.core.model.user
@enduml
